name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

env:
  BASE_URL: https://releases.sailfishos.org/sdk/installers/3.6.6
  CHROOT_IMAGE: Sailfish_OS-Jolla_SDK-4.2.0.21-Platform_SDK_Chroot-i486.tar.bz2

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/dseight/sailfishos-sdk-chroot
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Download Sailfish OS Chroot tarball
        run: curl ${{ env.BASE_URL }}/${{ env.CHROOT_IMAGE }} -o ./${{ env.CHROOT_IMAGE }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            CHROOT_IMAGE=./${{ env.CHROOT_IMAGE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
